ÁGUA GRANDE PORTE = 
VAR MEDIA_AGUA_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaAgua/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_AGUA_GP,

BLANK())