ÁGUA MÉDIO PORTE = 
VAR MEDIA_AGUA_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaAgua/PorteMedio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_AGUA_GM,

BLANK())