ÁGUA PEQUENO PORTE = 
VAR MEDIA_AGUA_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaAgua/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_AGUA_GP,

BLANK())