ALUGUEL GRANDE PORTE = 
VAR MEDIA_ALUGUEL_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaAluguel/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_ALUGUEL_GP,

BLANK())