ALUGUEL PEQUENO PORTE = 
VAR MEDIA_ALUGUEL_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaAluguel/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_ALUGUEL_GP,

BLANK())