CÓPIAS MÉDIO PORTE = 
VAR MEDIA_COPIAS_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaCopias/PorteMedio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_COPIAS_GM,

BLANK())