CÓPIAS GRANDE PORTE = 
VAR MEDIA_COPIAS_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaCopias/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_COPIAS_GP,

BLANK())