CÓPIAS PEQUENO PORTE = 
VAR MEDIA_COPIAS_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaCopias/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_COPIAS_GP,

BLANK())