DESP VEÍCULOS PEQUENO PORTE = 
VAR MEDIA_DESPVEICULOS_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaDespVeiculoss/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_DESPVEICULOS_GP,

BLANK())