DESP VEÍCULOS MÉDIO PORTE = 
VAR MEDIA_DESPVEICULOS_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaDespVeiculos/PorteMedio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_DESPVEICULOS_GM,

BLANK())