DESP VEÍCULOS GRANDE PORTE = 
VAR MEDIA_DESPVEICULOS_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaDespVeiculos/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_DESPVEICULOS_GP,

BLANK())