ESTAG TERCEIROS GRANDE PORTE = 
VAR MEDIA_ESTAGTERCEIROS_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaEstagTerceiros/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_ESTAGTERCEIROS_GP,

BLANK())