ESTAG TERCEIROS MÉDIO PORTE = 
VAR MEDIA_ESTAGTERCEIROS_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaEstagTerceiros/PorteMedio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_ESTAGTERCEIROS_GM,

BLANK())