ESTAG TERCEIROS PEQUENO PORTE = 
VAR MEDIA_ESTAGTERCEIROS_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaEstagTerceiros/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_ESTAGTERCEIROS_GP,

BLANK())