FOLHA MÉDIO PORTE = 
VAR MEDIA_FOLHA_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaFolha/PorteMédio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_FOLHA_GM,

BLANK())