FOLHA PEQUENO PORTE = 
VAR MEDIA_FOLHA_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaFolha/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_FOLHA_GP,

BLANK())