FOLHA GRANDE PORTE = 
VAR MEDIA_FOLHA_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaFolha/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_FOLHA_GP,

BLANK())