IPTU MÉDIO PORTE = 
VAR MEDIA_IPTU_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaIPTU/PorteMedio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_IPTU_GM,

BLANK())