IPTU PEQUENO PORTE = 
VAR MEDIA_IPTU_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaIPTU/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_IPTU_GP,

BLANK())