IPTU GRANDE PORTE = 
VAR MEDIA_IPTU_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaIPTU/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_IPTU_GP,

BLANK())