LIMPEZA MÉDIO PORTE = 
VAR MEDIA_LIMPEZA_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaLimpeza/PorteMedio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_LIMPEZA_GM,

BLANK())