LIMPEZA GRANDE PORTE = 
VAR MEDIA_LIMPEZA_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaLimpeza/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_LIMPEZA_GP,

BLANK())