LIMPEZA PEQUENO PORTE = 
VAR MEDIA_LIMPEZA_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaLimpeza/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_LIMPEZA_GP,

BLANK())