MANUTENÇÃO MÉDIO PORTE = 
VAR MEDIA_MANUTENCAO_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaManutencao/PorteMedio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_MANUTENCAO_GM,

BLANK())