MANUTENÇÃO GRANDE PORTE = 
VAR MEDIA_MANUTENCAO_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaManutencao/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_MANUTENCAO_GP,

BLANK())