MANUTENÇÃO PEQUENO PORTE = 
VAR MEDIA_MANUTENCAO_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaManutecacao/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_MANUTENCAO_GP,

BLANK())