MediaDespVeiculos/PorteMedio9 = 
VAR MEDIDA = [MediaDespVeiculos/PorteMedio]

VAR CONTAGEMESCRITORIOS = CALCULATE(COUNT(dimLocal[Local]), FILTER(dimLocal, dimLocal[PorteER] = "MÉDIO PORTE"))

RETURN DIVIDE(MEDIDA, CONTAGEMESCRITORIOS)