MediaEstagTerceiros/PorteGrande16 = 
VAR MEDIDA = [MediaEstagTerceiros/PorteGrande]

VAR CONTAGEMESCRITORIOS = CALCULATE(COUNT(dimLocal[Local]), FILTER(dimLocal, dimLocal[PorteER] = "GRANDE PORTE"))

RETURN DIVIDE(MEDIDA, CONTAGEMESCRITORIOS)