MediaFuncionario/PorteGrande16 = 
VAR NUMEROFUNCIONARIO = 
CALCULATE(
  [SomaFuncionario], FILTER(dimLocal, dimLocal[PorteER] = "GRANDE PORTE"
))

VAR CONTAGEMESCRITORIOS = CALCULATE(COUNT(dimLocal[Local]), FILTER(dimLocal, dimLocal[PorteER] = "GRANDE PORTE"))

RETURN DIVIDE(NUMEROFUNCIONARIO, CONTAGEMESCRITORIOS)