MediaIPTU/PortePequeno8 = 
VAR MEDIDA = [MediaIPTU/PortePequeno]

VAR CONTAGEMESCRITORIOS = CALCULATE(COUNT(dimLocal[Local]), FILTER(dimLocal, dimLocal[PorteER] = "PEQUENO PORTE"))

RETURN DIVIDE(MEDIDA, CONTAGEMESCRITORIOS)