OUTROS GRANDE PORTE = 
VAR MEDIA_OUTROS_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaOutros/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_OUTROS_GP,

BLANK())