OUTROS PEQUENO PORTE = 
VAR MEDIA_OUTROS_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaOutros/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_OUTROS_GP,

BLANK())