TELE COMUNICAÇÃO PEQUENO PORTE = 
VAR MEDIA_TELECOMUNICACAO_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaTeleComunicacao/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_TELECOMUNICACAO_GP,

BLANK())