TELE COMUNICAÇÃO GRANDE PORTE = 
VAR MEDIA_TELECOMUNICACAO_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaTeleComunicacao/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_TELECOMUNICACAO_GP,

BLANK())