VIGILÂNCIA GRANDE PORTE = 
VAR MEDIA_VIGILANCIA_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaVigilancia/PorteGrande],
    [CONTAGEM DISTINTA DE ER DE GRANDE PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE GRANDE PORTE",
MEDIA_VIGILANCIA_GP,

BLANK())