VIGILÂNCIA PEQUENO PORTE = 
VAR MEDIA_VIGILANCIA_GP =
    CALCULATE(
        
        DIVIDE(
    [MediaVigilancia/PortePequeno],
    [CONTAGEM DISTINTA DE ER DE PEQUENO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE PEQUENO PORTE",
MEDIA_VIGILANCIA_GP,

BLANK())