VIGILÂNCIA MÉDIO PORTE = 
VAR MEDIA_VIGILANCIA_GM =
    CALCULATE(
        
        DIVIDE(
    [MediaVigilancia/PorteMedio],
    [CONTAGEM DISTINTA DE ER DE MÉDIO PORTE]
),

REMOVEFILTERS(fER[CLASSIFICA]))
RETURN
IF(
    
    SELECTCOLUMNS(fER,fER[Porte ERs]) = "ER DE MÉDIO PORTE",
MEDIA_VIGILANCIA_GM,

BLANK())